### ISSUE TITLE
In the apply_coupons final "result" example

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/green_grocer#2]
The count for the "AVOCADO W/COUPON" needs to be changed to 2.

SO:

This is what it looks like:
{
  "AVOCADO" => {:price => 3.0, :clearance => true, :count => 1},
  "KALE"    => {:price => 3.0, :clearance => false, :count => 1},
  "AVOCADO W/COUPON" => {:price => 5.0, :clearance => true, :count => 1},
}

And this is what is needs to be changed to:

{
  "AVOCADO" => {:price => 3.0, :clearance => true, :count => 1},
  "KALE"    => {:price => 3.0, :clearance => false, :count => 1},
  "AVOCADO W/COUPON" => {:price => 5.0, :clearance => true, :count => 2},
}

**Comment by garettarrowood** [comment]
Or perhaps I'm wrong.  Then maybe the name needs to be changed to "AVOCADOS W/COUPON".

**Comment by BenjaGross** [comment]
@garettarrowood I'm not totally sure if you are talking about a spec or a method or students suggested code here. 

Can you create a pull request with your proposed changes to this lab?

**Comment by garettarrowood** [comment]
@BenjaGross I think this lab is perfect as is. I ran into confusion with the key of the coupon in relationship to the :count value, since 2 avocados were being subtracted from the total but the :count was only 1.  But after spending a little while wrapping my brain around the lab, realizing that the :count value represents the number of coupons and not the number of avocados, I don't think their is a better wording for this lab.

**Comment by BenjaGross** [comment]
@garettarrowood I agree, we definitely should change the wording around in that lab to make it a little more explicit.

**Comment by AnnJohn** [comment]
Iceboxing for now
