### ISSUE TITLE
keyword arguments is confusing

### ISSUE THREAD

**Issue by ipc103** [learn-co-curriculum/green_grocer#4]
Keyword arguments confused students here - does that topic need to be introduced here? This lab is very challenging in general, and that's an extra layer of confusion for them. We should remove keyword arguments from this lab.

**Comment by AnnJohn** [comment]
hi @PeterBell, again not a huge priority right now but this is a lab that we use in our immersive curriculum that's been challenging for students in the past, in part because of the above issue. thanks

**Comment by PeterBell** [comment]
Hi @AnnJohn I don't feel I have a good enough handle on the overall curriculum and the place of this lesson in it to speak to this. I'm open to whatever is suggested by @ipc103 and/or @pletcher

**Comment by pletcher** [comment]
It seems to me that the note at the bottom offers sufficient explanation. This lesson shows up towards the end of the intro Ruby stuff, which seems like about the right place.

<img width="293" alt="screen shot 2016-04-06 at 11 51 24 am" src="https://cloud.githubusercontent.com/assets/2015049/14323304/02934120-fbee-11e5-96f5-885d399f8cb5.png">

Is there something in particular that students are having trouble with? kwargs in Ruby are a little weird.

**Comment by ipc103** [comment]
My two cents:

This is typically one of the most difficult labs in the curriculum.
Students are still learning to work manipulating nested data structures.
Adding in keyword arguments here as something new to learn just feels
unnecessary.

My suggestion would be to make a separate README and/or lab to teach about
keyword arguments. If we want to keep this included with an existing lab,
we should pick an easier lab to teach it with.

On Wed, Apr 6, 2016 at 11:53 AM, Charles Pletcher <notifications@github.com>
wrote:

> It seems to me that the note at the bottom offers sufficient explanation.
> This lesson shows up towards the end of the intro Ruby stuff, which seems
> like about the right place.
>
> [image: screen shot 2016-04-06 at 11 51 24 am]
> <https://cloud.githubusercontent.com/assets/2015049/14323304/02934120-fbee-11e5-96f5-885d399f8cb5.png>
>
> Is there something in particular that students are having trouble with?
> kwargs in Ruby are a little weird.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/learn-co-curriculum/green_grocer/issues/4#issuecomment-206439439>
>



-- 
Ian Candy
 Web Instructor, Flatiron School

**Comment by pletcher** [comment]
That makes sense -- if they're not needed for this lab, we can remove them. They can be added in someplace that makes sense at a later date.

**Comment by pletcher** [comment]
Fixed https://github.com/learn-co-curriculum/green_grocer/commit/73072f6fb73ecea61684e109b8655d032659c65d
